project:
  type: website
  output-dir: docs

website:
  title: "Anna Côté"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - href: /resume_for_website.pdf # file path for resume.pdf
        text: Resume
        target: _blank # opening page in new browser tab
      - href: projects.qmd
        text: Projects
      - href: freeforall.qmd
        text: Free For All
page-footer:
  left: Copyright 2025, Anna Côté

      

format:
  html:
    theme: 
      - cosmo
      - styles.scss
    toc: true
    page-layout: full
    

editor: visual