project:
  type: website
  output-dir: docs

website:
  title: "Anna Cote"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - resume.qmd
      - projects.qmd
      - freeforall.qmd
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full
    

editor: visual

