project:
  type: website
  output-dir: docs

website:
  title: "Anna Côté"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - href: /resume_for_website.pdf # file path for resume.pdf
        text: Resume
        target: _blank # opening page in new browser tab
      - href: posts.qmd
      - href: foodforthought.qmd
      
page-footer:
  left: "Copyright 2025, Anna Côté"
      

format:
  html:
    theme: 
      - cosmo
      - styles.scss
    mainfont: EB Garamond
    css: styles.css
    toc: true
    page-layout: full
    

editor: visual