project:
  type: website
  output-dir: docs

website:
  title: "Anna Côté"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - href: /resume_for_website.pdf
        text: Resume
      - href: projects.qmd
        text: Projects
      - href: freeforall.qmd
        text: Free For All

      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full
    

editor: visual